openapi: 3.0.0
info:
  title: Loan Service API
  version: 1.0.0
paths:
  /service/v1/loansByUser/{userId}:
    get:
      summary: Retrieve loans for a specific user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user for whom to retrieve loans
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Loan'
              example:
                id: "12345-a12-b3458-c6545"
                loanType: "ParentLoan"
                name: "Loan 1"
                contractNumber: "12345.67"
                loanStatus: "active"
                currencyCode: "USD"
                outstandingAmount: "1954.94"
                creditLimit: "2000"
                interestRate: "5.00000"
                interestDue: "88.30000"
                isOverdue: false
                parentLoanId: "12345-a12-b3458-c6545"
                startDate: "1996-10-23T17:00:00.000Z"
                endDate: "2022-10-23T17:00:00.000Z"
                borrower:
                  - "John Doe"
                  - "Robert Cain"
                defaultSettlementAccountNumber: "CH12 1234 45678 1230"
                paymentFrequency: "Monthly"
                interestPaymentFrequency: "Quarterly"
                collateral:
                  - type: "Real Estate"
                    currentValue: "100"
                    currencyCode: "CHF"
                    specification: "Lagerstrasse 10, 8001 Zuerich"
                    nextRevaluationDate: "2021-02-28"
                    AmortisationPaymentAmount: "100.00"
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: "Unauthorized"
                message: "Authentication failed"
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: "Internal Server Error"
                message: "An unexpected error occurred"
components:
  schemas:
    Loan:
      type: object
      properties:
        id:
          type: string
          description: UUID of the loan
        loanType:
          type: string
          enum:
            - ParentLoan
            - ChildLoan
          description: Type of the loan
        name:
          type: string
          description: Name of the loan
        contractNumber:
          type: string
          description: Contract Number of the loan
        loanStatus:
          type: string
          enum:
            - active
            - inactive
          description: Status of the loan
        currencyCode:
          type: string
          description: ISO3 currency code
        outstandingAmount:
          type: string
          description: Outstanding amount of the loan
        creditLimit:
          type: string
          description: Overall allowed limit of the loan
        interestRate:
          type: string
          description: Interest rate for the given loan
        interestDue:
          type: string
          description: Interest amount which is due
        isOverdue:
          type: boolean
          description: Boolean value indicating whether an interest is due or not
        parentLoanId:
          type: string
          description: Reference to the UUID of the parent loan
        startDate:
          type: string
          format: date-time
          description: Start date of the loan
        endDate:
          type: string
          format: date-time
          description: Maturity date of the loan
        borrower:
          type: array
          items:
            type: string
          description: Array displaying the names of the client(s) who took the loan
        defaultSettlementAccountNumber:
          type: string
          description: Account number where the settlement payments are made by default
        paymentFrequency:
          type: string
          description: Frequency of the loan payment
        interestPaymentFrequency:
          type: string
          description: Frequency of the interest payment
        collateral:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum:
                  - Einfamilienhaus
                  - Reihenhaus
                  - Stockwerkeigentum
                  - Mehrfamilienhaus
                  - Gartenhaus
                  - Bauland
                description: Type of the collateral
              currentValue:
                type: string
                description: Current valuation of the collateral
              currencyCode:
                type: string
                description: Currency of the valuation of the collateral
              specification:
                type: string
                description: Address of the collateral
              nextRevaluationDate:
                type: string
                format: date
                description: Date of the next valuation of the collateral
              AmortisationPaymentAmount:
                type: string
                description: Amount of the amortisation payment
          description: Information about the collateral
